apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: presenterte-kandidater
    namespace: toi
    labels:
        team: toi
spec:
    groups:
        - name: presenterte-kandidater
          rules:
              - alert: presenterte-kandidater
                expr: kube_deployment_status_replicas_available{deployment="presenterte-kandidater"} == 0
                for: 1s
                annotations:
                    summary: Appen er nede
                    action: "https://logs.az.nav.no/goto/445fe3911040a2bef9d12ac5a8e70a7a?security_tenant=navlogs"
                labels:
                    namespace: toi
                    severity: critical

              - alert: presenterte-kandidater
                expr: sum(increase(log_messages_errors{app="presenterte-kandidater", level="Error"}[10m])) > 0
                for: 1s
                annotations:
                    summary: Appen har logget en error
                    action: "https://logs.az.nav.no/goto/445fe3911040a2bef9d12ac5a8e70a7a?security_tenant=navlogs"
                labels:
                    namespace: toi
                    severity: critical

              - alert: presenterte-kandidater
                expr: sum(increase(log_messages_errors{app="presenterte-kandidater", level="Warning"}[10m])) > 3
                for: 1s
                annotations:
                    summary: Økning i warnings
                    action: "https://logs.az.nav.no/goto/445fe3911040a2bef9d12ac5a8e70a7a?security_tenant=navlogs"
                labels:
                    namespace: toi
                    severity: warning
