apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: presenterte-kandidater
  namespace: toi
  labels:
    team: toi
spec:
  # prettier-ignore
  image: {{ image }}
  port: 3000
  replicas:
    min: {{ min_replicas }}
  resources:
    requests:
      cpu: 50m
  ingresses:
    {{#each ingresses as |url|}}
        - {{ url }}
      {{/each}}
  liveness:
    initialDelay: 20
    path: /kandidatliste/api/internal/isAlive
  readiness:
    initialDelay: 20
    path: /kandidatliste/api/internal/isReady
  accessPolicy:
    outbound:
      rules:
        - application: presenterte-kandidater-api
        - application: nav-dekoratoren
          namespace: personbruker
        - application: notifikasjon-bruker-api
          namespace: fager
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      autoLogin: false
      autoLoginIgnorePaths:
        - /kandidatliste/api/internal/*
  envFrom:
    - secret: presenterte-kandidater-toggle
  env:
    - name: PRESENTERT_KANDIDATER_API
      value: http://presenterte-kandidater-api
    - name: NOTIFIKASJON_API_URL
      value: http://notifikasjon-bruker-api.fager
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
